[package]
name = "commit-block"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.28.1"
reqwest = { version = "0.12.7", features = [ "blocking", "json" ]}
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
dotenv = "0.15.0"
serde_json = "1.0.128"
chrono = "0.4.38"
